<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="System.Threading.RateLimiting" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClimateHub.SharedKernel\ClimateHub.SharedKernel.csproj" />
    <ProjectReference Include="..\ClimateHub.Infrastructure\ClimateHub.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Building\ClimateHub.Modules.Building.Application\ClimateHub.Modules.Building.Application.csproj" />
    <ProjectReference Include="..\Modules\Building\ClimateHub.Modules.Building.Infrastructure\ClimateHub.Modules.Building.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Devices\ClimateHub.Modules.Devices.Application\ClimateHub.Modules.Devices.Application.csproj" />
    <ProjectReference Include="..\Modules\Devices\ClimateHub.Modules.Devices.Infrastructure\ClimateHub.Modules.Devices.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Environment\ClimateHub.Modules.Environment.Infrastructure\ClimateHub.Modules.Environment.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Commands\ClimateHub.Modules.Commands.Application\ClimateHub.Modules.Commands.Application.csproj" />
    <ProjectReference Include="..\Modules\Commands\ClimateHub.Modules.Commands.Infrastructure\ClimateHub.Modules.Commands.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Needs\ClimateHub.Modules.Needs.Infrastructure\ClimateHub.Modules.Needs.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\EngineeringSystems\ClimateHub.Modules.EngineeringSystems.Infrastructure\ClimateHub.Modules.EngineeringSystems.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\EngineeringSystems\ClimateHub.Modules.EngineeringSystems.Application\ClimateHub.Modules.EngineeringSystems.Application.csproj" />
    <ProjectReference Include="..\Modules\EngineeringSystems\ClimateHub.Modules.EngineeringSystems.Domain\ClimateHub.Modules.EngineeringSystems.Domain.csproj" />
    <ProjectReference Include="..\Modules\Climate\ClimateHub.Modules.Climate.Infrastructure\ClimateHub.Modules.Climate.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Climate\ClimateHub.Modules.Climate.Application\ClimateHub.Modules.Climate.Application.csproj" />
    <ProjectReference Include="..\Modules\IAM\ClimateHub.Modules.IAM.Domain\ClimateHub.Modules.IAM.Domain.csproj" />
    <ProjectReference Include="..\Modules\IAM\ClimateHub.Modules.IAM.Application\ClimateHub.Modules.IAM.Application.csproj" />
    <ProjectReference Include="..\Modules\IAM\ClimateHub.Modules.IAM.Infrastructure\ClimateHub.Modules.IAM.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\IAM\ClimateHub.Modules.IAM.Contracts\ClimateHub.Modules.IAM.Contracts.csproj" />
  </ItemGroup>
</Project>