<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClimateHub.Modules.Building.Domain\ClimateHub.Modules.Building.Domain.csproj" />
    <ProjectReference Include="..\ClimateHub.Modules.Building.Application\ClimateHub.Modules.Building.Application.csproj" />
    <ProjectReference Include="..\ClimateHub.Modules.Building.Contracts\ClimateHub.Modules.Building.Contracts.csproj" />
    <ProjectReference Include="..\..\..\ClimateHub.Infrastructure\ClimateHub.Infrastructure.csproj" />
  </ItemGroup>
</Project>