global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'climate-hub-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: /metrics
    scheme: http

  - job_name: 'climate-hub-gateway'
    static_configs:
      - targets: ['device-gateway:5001']
    metrics_path: /metrics
    scheme: http

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']