<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\ClimateHub.SharedKernel\ClimateHub.SharedKernel.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ClimateHub.Modules.Commands.Contracts</RootNamespace>
  </PropertyGroup>
</Project>